'use client'

import { useState } from 'react'
import {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronRight,
  Clock3,
  Coffee,
  Home,
  Minus,
  PackageCheck,
  Plus,
  ReceiptText,
  Search,
  ShoppingBag,
  Sparkles,
  Utensils,
  X,
} from 'lucide-react'

type Item = { id: string; name: string; description: string; price: number; category: string; image: string; veg?: boolean }
type CartLine = { item: Item; quantity: number; addOns: string[]; note?: string }
type View = 'welcome' | 'menu' | 'cart' | 'checkout' | 'payment' | 'confirmed' | 'tracking' | 'orders'

const items: Item[] = [
  { id: 'chicken-burger', name: 'Chicken Burger', description: 'Grilled chicken, cheese, lettuce & house sauce', price: 180, category: 'Burgers', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85' },
  { id: 'veg-burger', name: 'Veg Burger', description: 'Crispy vegetable patty, cheese & fresh greens', price: 150, category: 'Burgers', image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=85', veg: true },
  { id: 'fries', name: 'French Fries', description: 'Golden, crisp and lightly seasoned', price: 100, category: 'Snacks', image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85', veg: true },
  { id: 'cold-coffee', name: 'Cold Coffee', description: 'Smooth coffee, chilled milk & a little sweetness', price: 120, category: 'Beverages', image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=85', veg: true },
  { id: 'cappuccino', name: 'Cappuccino', description: 'Rich espresso with silky steamed milk foam', price: 110, category: 'Coffee', image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=900&q=85', veg: true },
  { id: 'chocolate-cake', name: 'Chocolate Cake', description: 'Warm chocolate sponge with ganache', price: 160, category: 'Desserts', image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85', veg: true },
  { id: 'chicken-pizza', name: 'Chicken Pizza', description: 'Roasted chicken, mozzarella and herbs', price: 280, category: 'Pizza', image: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=85' },
  { id: 'latte', name: 'Latte', description: 'Espresso, steamed milk and a soft finish', price: 130, category: 'Coffee', image: 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=900&q=85', veg: true },
]
const categories = ['All', 'Breakfast', 'Main Course', 'Snacks', 'Burgers', 'Pizza', 'Coffee', 'Beverages', 'Desserts']
const money = (n: number) => `₹${n.toLocaleString('en-IN')}`

export default function Page() {
  const params = typeof window !== 'undefined' ? new URLSearchParams(window.location.search) : null
  const table = params?.get('table') || '12'
  const validTable = !params || /^\d+$/.test(table)
  const [view, setView] = useState<View>(validTable ? 'welcome' : 'welcome')
  const [category, setCategory] = useState('All')
  const [query, setQuery] = useState('')
  const [cart, setCart] = useState<CartLine[]>([])
  const [selected, setSelected] = useState<Item | null>(null)
  const [qty, setQty] = useState(1)
  const [addOns, setAddOns] = useState<string[]>([])
  const [note, setNote] = useState('')
  const [payment, setPayment] = useState<'online' | 'counter'>('counter')
  const [toast, setToast] = useState('')

  const filtered = items.filter((item) => (category === 'All' || item.category === category) && `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase()))
  const count = cart.reduce((sum, line) => sum + line.quantity, 0)
  const subtotal = cart.reduce((sum, line) => sum + line.quantity * (line.item.price + line.addOns.reduce((s, a) => s + ({ 'Extra Cheese': 30, 'Extra Patty': 60, 'Extra Sauce': 20 }[a] || 0), 0)), 0)
  const tax = Math.round(subtotal * 0.05)
  const total = subtotal + tax
  const selectedTotal = selected ? (selected.price + addOns.reduce((s, a) => s + ({ 'Extra Cheese': 30, 'Extra Patty': 60, 'Extra Sauce': 20 }[a] || 0), 0)) * qty : 0

  function showToast(message: string) { setToast(message); window.setTimeout(() => setToast(''), 2200) }
  function addToCart(item: Item, quantity = 1, options: string[] = [], instruction = '') { setCart((current) => [...current, { item, quantity, addOns: options, note: instruction }]); showToast(`${item.name} added`); setSelected(null); setQty(1); setAddOns([]); setNote('') }
  function changeLine(index: number, delta: number) { setCart((current) => current.map((line, i) => i === index ? { ...line, quantity: Math.max(0, line.quantity + delta) } : line).filter((line) => line.quantity > 0)) }

  if (!validTable) return <Shell><div className="flex min-h-dvh flex-col items-center justify-center px-8 text-center"><div className="mb-6 grid size-20 place-items-center rounded-full bg-[#ead9ca] text-[#4a2d20]"><X size={34}/></div><h1 className="font-serif text-3xl font-semibold text-[#2c211b]">Invalid Table QR</h1><p className="mt-3 text-[#77685f]">We couldn&apos;t identify your table.</p><button className="primary-button mt-8" onClick={() => location.reload()}>Try Again</button></div></Shell>

  return <Shell>
    {view === 'welcome' && <Welcome table={table} onStart={() => setView('menu')} />}
    {view === 'menu' && <><Header table={table} count={count} onCart={() => setView('cart')} /><main className="px-5 pb-28 pt-7"><p className="eyebrow">Good evening</p><h1 className="mt-1 font-serif text-[34px] leading-tight text-[#2c211b]">What would you like<br/>to have?</h1><div className="search-box mt-6"><Search size={19}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search food or drinks" aria-label="Search food or drinks"/></div><div className="no-scrollbar -mx-5 flex gap-2 overflow-x-auto px-5 py-5">{categories.map((cat) => <button key={cat} onClick={() => setCategory(cat)} className={`category-chip ${category === cat ? 'active' : ''}`}>{cat}</button>)}</div>{filtered.length ? <div className="flex flex-col gap-4">{filtered.map((item) => <MenuCard key={item.id} item={item} onAdd={() => addToCart(item)} onOpen={() => { setSelected(item); setQty(1); setAddOns([]) }} />)}</div> : <div className="rounded-3xl bg-white p-8 text-center"><Search className="mx-auto text-[#b17a5b]"/><p className="mt-4 font-semibold">No dishes found</p><p className="mt-1 text-sm text-[#77685f]">Try another search or category.</p></div>}</main><BottomNav active="menu" onMenu={() => setView('menu')} onOrders={() => setView('orders')} onHome={() => setView('menu')} /></>}
    {view === 'cart' && <CartView table={table} cart={cart} subtotal={subtotal} tax={tax} total={total} onBack={() => setView('menu')} onChange={changeLine} onMore={() => setView('menu')} onCheckout={() => setView('checkout')} />}
    {view === 'checkout' && <Checkout table={table} cart={cart} subtotal={subtotal} tax={tax} total={total} payment={payment} setPayment={setPayment} onBack={() => setView('cart')} onPlace={() => setView(payment === 'online' ? 'payment' : 'confirmed')} />}
    {view === 'payment' && <Payment total={total} onBack={() => setView('checkout')} onSuccess={() => setView('confirmed')} />}
    {view === 'confirmed' && <Confirmed total={total} payment={payment} onTrack={() => setView('tracking')} onMore={() => setView('menu')} />}
    {view === 'tracking' && <Tracking total={total} onMore={() => setView('menu')} />}
    {view === 'orders' && <Orders onBack={() => setView('menu')} onMore={() => setView('menu')} />}
    {selected && <ItemSheet item={selected} qty={qty} setQty={setQty} addOns={addOns} setAddOns={setAddOns} note={note} setNote={setNote} total={selectedTotal} onClose={() => setSelected(null)} onAdd={() => addToCart(selected, qty, addOns, note)} />}
    {toast && <div className="toast"><Check size={17}/> {toast}</div>}
  </Shell>
}

function Shell({ children }: { children: React.ReactNode }) { return <div className="mx-auto min-h-dvh max-w-[430px] bg-[#f8f3ed] shadow-2xl">{children}</div> }
function Welcome({ table, onStart }: { table: string; onStart: () => void }) { return <main className="relative flex min-h-dvh flex-col overflow-hidden bg-[#38251e] text-[#fffaf4]"><img className="absolute inset-0 size-full object-cover opacity-60" src="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=90" alt="Warm coffee and café table"/><div className="absolute inset-0 bg-gradient-to-b from-[#241712]/30 via-[#241712]/20 to-[#241712]"/><div className="relative flex flex-1 flex-col justify-between p-7"><div className="flex items-center justify-between"><div><p className="brand-light">TERMINAL <span>2</span></p><p className="mt-1 text-xs tracking-[.2em] text-[#e8d4c3]">COIMBATORE, TAMIL NADU</p></div><div className="table-badge light">TABLE {table}</div></div><div className="pb-5"><div className="mb-7 flex items-center gap-2 text-sm text-[#e8d4c3]"><Sparkles size={16}/> Your table, your way</div><h1 className="font-serif text-[52px] leading-[.96] tracking-tight">Welcome to<br/><em className="text-[#df9b70]">Terminal 2</em></h1><p className="mt-5 max-w-[280px] text-[17px] leading-relaxed text-[#eadbd0]">Order directly from your table. Freshly made, just for you.</p><button className="primary-button light mt-8 w-full" onClick={onStart}>View Menu <ArrowRight size={18}/></button><p className="mt-4 text-center text-xs text-[#cdb9aa]">No login required · Table {table}</p></div></div></main> }
function Header({ table, count, onCart }: { table: string; count: number; onCart: () => void }) { return <header className="flex items-center justify-between px-5 pt-7"><div><p className="brand">TERMINAL <span>2</span></p><div className="mt-2 flex items-center gap-2"><span className="table-dot"/> <span className="text-xs font-semibold tracking-wide text-[#705b4f]">TABLE {table}</span></div></div><button className="cart-button" onClick={onCart} aria-label="Open cart"><ShoppingBag size={21}/>{count > 0 && <span>{count}</span>}</button></header> }
function MenuCard({ item, onAdd, onOpen }: { item: Item; onAdd: () => void; onOpen: () => void }) { return <article className="menu-card"><button className="block w-full text-left" onClick={onOpen}><img src={item.image} alt={item.name} /><div className="p-4 pb-2"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className={`food-dot ${item.veg ? 'veg' : ''}`}/><h2 className="font-semibold text-[#33251e]">{item.name}</h2></div><p className="mt-1.5 max-w-[225px] text-[13px] leading-snug text-[#88766b]">{item.description}</p></div><span className="font-semibold text-[#4a2d20]">{money(item.price)}</span></div></div></button><div className="px-4 pb-4"><button className="add-button" onClick={onAdd}><Plus size={16}/> Add</button></div></article> }
function FooterBar({ children }: { children: React.ReactNode }) { return <div className="sticky bottom-0 z-20 mt-auto border-t border-[#eadfd5] bg-[#f8f3ed]/95 p-5 backdrop-blur">{children}</div> }
function PriceBreakdown({ subtotal, tax, total }: { subtotal: number; tax: number; total: number }) { return <div className="flex flex-col gap-3 border-t border-[#eadfd5] pt-4 text-sm"><div className="flex justify-between text-[#77685f]"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="flex justify-between text-[#77685f]"><span>Taxes & charges</span><span>{money(tax)}</span></div><div className="flex justify-between border-t border-[#eadfd5] pt-3 text-base font-bold text-[#33251e]"><span>Total</span><span>{money(total)}</span></div></div> }
function CartView({ table, cart, subtotal, tax, total, onBack, onChange, onMore, onCheckout }: any) { return <div className="flex min-h-dvh flex-col"><div className="flex items-center gap-4 px-5 pb-5 pt-7"><button className="icon-button" onClick={onBack}><ArrowLeft size={19}/></button><div><p className="eyebrow">TABLE {table}</p><h1 className="font-serif text-3xl text-[#2c211b]">Your Order</h1></div></div>{cart.length === 0 ? <div className="flex flex-1 flex-col items-center justify-center px-8 pb-24 text-center"><div className="mb-6 grid size-20 place-items-center rounded-full bg-[#ead9ca] text-[#8f5c40]"><ShoppingBag size={32}/></div><h2 className="font-serif text-2xl">Your cart is empty</h2><p className="mt-2 text-sm text-[#77685f]">Add something delicious from the menu.</p><button className="primary-button mt-7" onClick={onMore}>Browse Menu</button></div> : <><main className="flex flex-1 flex-col gap-4 px-5 pb-5">{cart.map((line: CartLine, index: number) => <div className="cart-line" key={`${line.item.id}-${index}`}><img src={line.item.image} alt=""/><div className="min-w-0 flex-1"><p className="font-semibold text-[#33251e]">{line.item.name}</p><p className="mt-1 text-sm text-[#77685f]">{money(line.item.price)} {line.addOns.length ? `· ${line.addOns.join(', ')}` : ''}</p><div className="quantity"><button onClick={() => onChange(index, -1)}><Minus size={14}/></button><span>{line.quantity}</span><button onClick={() => onChange(index, 1)}><Plus size={14}/></button></div></div><p className="font-semibold text-[#4a2d20]">{money(line.quantity * line.item.price)}</p></div>)}<button className="mt-1 flex items-center gap-2 text-sm font-semibold text-[#9a6245]" onClick={onMore}><Plus size={16}/> Add more items</button><PriceBreakdown subtotal={subtotal} tax={tax} total={total}/></main><FooterBar><button className="primary-button w-full" onClick={onCheckout}>Proceed to Checkout <ChevronRight size={18}/></button></FooterBar></>}</div> }
function Checkout({ table, cart, subtotal, tax, total, payment, setPayment, onBack, onPlace }: any) { return <div className="flex min-h-dvh flex-col"><div className="flex items-center gap-4 px-5 pb-6 pt-7"><button className="icon-button" onClick={onBack}><ArrowLeft size={19}/></button><div><p className="eyebrow">TABLE {table}</p><h1 className="font-serif text-3xl text-[#2c211b]">Review Order</h1></div></div><main className="flex flex-1 flex-col gap-7 px-5 pb-28"><section><p className="section-label">YOUR ITEMS</p><div className="mt-3 flex flex-col gap-3">{cart.map((line: CartLine, i: number) => <div className="flex justify-between text-sm" key={i}><span className="text-[#57473d]">{line.item.name} <span className="text-[#a28d80]">× {line.quantity}</span></span><span className="font-semibold">{money(line.item.price * line.quantity)}</span></div>)}</div></section><PriceBreakdown subtotal={subtotal} tax={tax} total={total}/><section><p className="section-label">HOW WOULD YOU LIKE TO PAY?</p><div className="mt-3 flex flex-col gap-3"><PayCard active={payment === 'online'} onClick={() => setPayment('online')} icon={<ReceiptText/>} title="Pay now" text="Pay securely online"/><PayCard active={payment === 'counter'} onClick={() => setPayment('counter')} icon={<Utensils/>} title="Pay at counter" text="Pay after your meal"/></div></section></main><FooterBar><button className="primary-button w-full" onClick={onPlace}>Place Order · {money(total)}</button></FooterBar></div> }
function PayCard({ active, onClick, icon, title, text }: any) { return <button onClick={onClick} className={`pay-card ${active ? 'active' : ''}`}><span className="pay-icon">{icon}</span><span className="flex-1 text-left"><strong className="block capitalize">{title}</strong><small>{text}</small></span>{active && <Check size={19}/>}</button> }
function Payment({ total, onBack, onSuccess }: any) { const [state, setState] = useState<'idle'|'processing'|'failed'>('idle'); return <div className="flex min-h-dvh flex-col"><div className="flex items-center gap-4 px-5 pb-6 pt-7"><button className="icon-button" onClick={onBack}><ArrowLeft size={19}/></button><div><p className="eyebrow">ORDER #1048</p><h1 className="font-serif text-3xl">Secure Payment</h1></div></div><main className="flex flex-1 flex-col px-5"><div className="rounded-3xl bg-[#38251e] p-6 text-[#fffaf4]"><p className="text-sm text-[#d9c2b2]">Amount to pay</p><p className="mt-2 font-serif text-4xl">{money(total)}</p><p className="mt-4 text-xs text-[#d9c2b2]">Prototype payment flow · no real charge</p></div><p className="section-label mt-8">CHOOSE PAYMENT METHOD</p><div className="mt-3 grid grid-cols-2 gap-3">{['UPI', 'Cards', 'Net Banking', 'Wallets'].map((x, i) => <button className={`payment-tile ${i === 0 ? 'selected' : ''}`} key={x}><span>{i === 0 ? '◉' : i === 1 ? '▣' : i === 2 ? '↔' : '▤'}</span>{x}</button>)}</div>{state === 'failed' && <div className="mt-7 rounded-2xl bg-[#f7e2df] p-4 text-sm text-[#8d3931]">Payment failed in this prototype. Please try again.</div>}</main><FooterBar>{state === 'processing' ? <button className="primary-button w-full" disabled><Clock3 className="animate-spin" size={18}/> Processing…</button> : <button className="primary-button w-full" onClick={() => { setState('processing'); setTimeout(onSuccess, 900) }}>{state === 'failed' ? 'Try Again' : `Pay ${money(total)}`}</button>}</FooterBar></div> }
function Confirmed({ total, payment, onTrack, onMore }: any) { return <div className="flex min-h-dvh flex-col items-center px-5 pb-8 pt-20 text-center"><div className="success-mark"><Check size={34}/></div><p className="eyebrow mt-7">ORDER #1048</p><h1 className="mt-2 font-serif text-4xl text-[#2c211b]">Order Confirmed!</h1><p className="mt-4 max-w-[280px] text-[#77685f]">Your order has been sent to the kitchen.</p><div className="mt-8 w-full rounded-3xl bg-white p-5 text-left"><div className="flex justify-between"><span className="text-sm text-[#77685f]">Table</span><strong>TABLE 12</strong></div><div className="mt-4 flex justify-between"><span className="text-sm text-[#77685f]">Estimated preparation</span><strong>15–20 min</strong></div><div className="mt-4 flex justify-between"><span className="text-sm text-[#77685f]">Payment</span><strong className="text-[#64805d]">{payment === 'online' ? 'PAID' : 'PAY AT COUNTER'}</strong></div><div className="mt-4 flex justify-between border-t border-[#eadfd5] pt-4"><span className="text-sm text-[#77685f]">Order total</span><strong>{money(total)}</strong></div></div><div className="mt-auto flex w-full flex-col gap-3 pt-10"><button className="primary-button w-full" onClick={onTrack}>Track Order <ArrowRight size={18}/></button><button className="text-sm font-semibold text-[#9a6245]" onClick={onMore}>Order More</button></div></div> }
function Tracking({ total, onMore }: any) { return <div className="flex min-h-dvh flex-col"><div className="px-5 pb-6 pt-8"><p className="eyebrow">TABLE 12</p><div className="mt-1 flex items-center justify-between"><h1 className="font-serif text-3xl">Order #1048</h1><span className="status-pill">Preparing</span></div></div><main className="flex flex-1 flex-col gap-7 px-5"><div className="rounded-3xl bg-[#38251e] p-6 text-[#fffaf4]"><div className="flex items-center gap-3"><Clock3 className="text-[#df9b70]"/><div><p className="text-sm text-[#d9c2b2]">Your food is being prepared</p><p className="mt-1 text-2xl font-semibold">Ready in ~10 min</p></div></div></div><div className="rounded-3xl bg-white p-5"><p className="section-label mb-5">ORDER STATUS</p>{['Order Received', 'Order Accepted', 'Preparing', 'Ready', 'Served'].map((s, i) => <div className="timeline-row" key={s}><span className={`timeline-dot ${i < 2 ? 'done' : i === 2 ? 'current' : ''}`}>{i < 2 ? <Check size={12}/> : i === 2 ? <span/> : ''}</span><span className={i === 2 ? 'font-semibold' : i < 2 ? 'text-[#57473d]' : 'text-[#b6a79e]'}>{s}</span></div>)}</div><div><p className="section-label">YOUR ORDER</p><div className="mt-3 flex justify-between text-sm"><span>Chicken Burger × 1</span><span className="font-semibold">{money(total)}</span></div><p className="mt-2 text-xs text-[#77685f]">Pay at counter · Table 12</p></div></main><FooterBar><button className="primary-button w-full" onClick={onMore}>Order More <Plus size={18}/></button></FooterBar></div> }
function Orders({ onBack, onMore }: any) { return <div className="flex min-h-dvh flex-col"><div className="flex items-center gap-4 px-5 pb-6 pt-7"><button className="icon-button" onClick={onBack}><ArrowLeft size={19}/></button><h1 className="font-serif text-3xl">Your Orders</h1></div><main className="flex flex-1 flex-col gap-4 px-5"><div className="order-card"><div className="flex justify-between"><div><p className="eyebrow">ORDER #1048</p><p className="mt-2 font-semibold">Chicken Burger + Fries</p></div><span className="status-pill">Preparing</span></div><div className="mt-5 flex justify-between border-t border-[#eadfd5] pt-4 text-sm"><span className="text-[#77685f]">Table 12 · Today</span><strong>₹280</strong></div></div><div className="order-card opacity-70"><div className="flex justify-between"><div><p className="eyebrow">ORDER #1039</p><p className="mt-2 font-semibold">Cold Coffee + Cake</p></div><span className="status-pill muted">Served</span></div><div className="mt-5 flex justify-between border-t border-[#eadfd5] pt-4 text-sm"><span className="text-[#77685f]">Table 12 · Today</span><strong>₹280</strong></div></div></main><FooterBar><button className="primary-button w-full" onClick={onMore}>Order More <Plus size={18}/></button></FooterBar></div> }
function ItemSheet({ item, qty, setQty, addOns, setAddOns, note, setNote, total, onClose, onAdd }: any) { const options = ['Extra Cheese', 'Extra Patty', 'Extra Sauce']; return <div className="sheet-backdrop" onClick={onClose}><section className="item-sheet" onClick={(e) => e.stopPropagation()}><button className="sheet-close" onClick={onClose}><X size={18}/></button><img src={item.image} alt={item.name}/><div className="p-5 pb-7"><div className="flex justify-between"><div><div className="flex items-center gap-2"><span className="food-dot"/><h2 className="font-serif text-2xl">{item.name}</h2></div><p className="mt-2 text-sm text-[#77685f]">{item.description}</p></div><strong className="text-[#4a2d20]">{money(item.price)}</strong></div><p className="section-label mt-7">CUSTOMIZE YOUR ORDER</p><div className="mt-3 flex flex-col gap-3">{options.map((option) => <label className="addon-row" key={option}><input type="checkbox" checked={addOns.includes(option)} onChange={() => setAddOns((a: string[]) => a.includes(option) ? a.filter((x) => x !== option) : [...a, option])}/><span>{option}</span><strong>+{money(({ 'Extra Cheese': 30, 'Extra Patty': 60, 'Extra Sauce': 20 } as any)[option])}</strong></label>)}</div><div className="mt-6 flex items-center justify-between"><p className="section-label">QUANTITY</p><div className="quantity"><button onClick={() => setQty(Math.max(1, qty - 1))}><Minus size={14}/></button><span>{qty}</span><button onClick={() => setQty(qty + 1)}><Plus size={14}/></button></div></div><textarea className="note-input mt-6" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Any special instructions?"/><button className="primary-button mt-5 w-full" onClick={onAdd}>Add to Cart — {money(total)}</button></div></section></div> }
function BottomNav({ active, onHome, onMenu, onOrders }: any) { return <nav className="bottom-nav"><button className={active === 'home' ? 'active' : ''} onClick={onHome}><Home size={19}/><span>Home</span></button><button className={active === 'menu' ? 'active' : ''} onClick={onMenu}><Coffee size={19}/><span>Menu</span></button><button className={active === 'orders' ? 'active' : ''} onClick={onOrders}><PackageCheck size={19}/><span>Orders</span></button></nav> }
